In [2]:
import numpy as np
from scipy import linalg
import time as time
import sys

#def creatToeplitz_Matrix(ru_min,ru_max,n):
ru_max=10
ru_min=0
n=50
h = (ru_max - ru_min)/n
A= np.zeros((n,n), dtype=float)
a = 2.0/h**2
b = -1.0/h**2
A[0,0]=a
A[0,1]=b
A[n-1,n-1]=a
A[n-1,n-2]=b
for i in range(1,n-1):
    A[i,i]=a
    A[i,i+1] = b
    A[i,i-1]=b
print (A)
    
for i in range (0 ,3):
    lamda=a+2*b*np.cos((i*3.14)/(n+1))
    print (lamda)
#print (A)
w,v=linalg.eig(A)
w=np.sort(w)
print(w)

#print(A)
   # return A

[[ 50. -25.   0. ...   0.   0.   0.]
 [-25.  50. -25. ...   0.   0.   0.]
 [  0. -25.  50. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...  50. -25.   0.]
 [  0.   0.   0. ... -25.  50. -25.]
 [  0.   0.   0. ...   0. -25.  50.]]
0.0
0.09473746473877753
0.37859085146608606
[9.48335631e-02+0.j 3.78974516e-01+0.j 8.51345016e-01+0.j
 1.51015320e+00+0.j 2.35289998e+00+0.j 3.37638853e+00+0.j
 4.57673641e+00+0.j 5.94939029e+00+0.j 7.48914321e+00+0.j
 9.19015438e+00+0.j 1.10459713e+01+0.j 1.30495541e+01+0.j
 1.51933027e+01+0.j 1.74690850e+01+0.j 1.98682682e+01+0.j
 2.23817514e+01+0.j 2.50000000e+01+0.j 2.77130822e+01+0.j
 3.05107063e+01+0.j 3.33822600e+01+0.j 3.63168505e+01+0.j
 3.93033458e+01+0.j 4.23304173e+01+0.j 4.53865820e+01+0.j
 4.84602471e+01+0.j 5.15397529e+01+0.j 5.46134180e+01+0.j
 5.76695827e+01+0.j 6.06966542e+01+0.j 6.36831495e+01+0.j
 6.66177400e+01+0.j 6.94892937e+01+0.j 7.22869178e+01+0.j
 7.50000000e+01+0.j 7.76182486e+01+0.j 8.01317318e+01+0.j
 8.25309150e+01+0.j 8.48066973e+